//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace frst_db_entity_framweork_again.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_student
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Fname { get; set; }
        [EmailAddress]
        public string Email { get; set; }

        [MinLength(11,ErrorMessage ="should not  exceed 11")]
        public string Mobile { get; set; }
        public string Description { get; set; }
    }
}
